engine = "text-davinci-003"
temperature = 0.3
n = 1
top_p = 1
frequency_penalty = 0
presence_penalty = 0
max_tokens = 2000
prompt_template = """
Write a user guide for the following code in Markdown format. Include instructions for running the code along with any optoins.

{{__INPUT__}}

User guide:
"""
