engine = "text-davinci-003"
temperature = 0.3
n = 1
top_p = 1
frequency_penalty = 0
presence_penalty = 0
max_tokens = 2000
prompt_template = """
Review the following code. Cite specific examples of:

- Potential bugs or security flaws
- Redundant code
- Code that is hard to read or not idiomatic

{{__INPUT__}}

# Problems:

-
"""