engine = "text-davinci-003"
temperature = 0.3
n = 1
top_p=1
frequency_penalty = 0
presence_penalty = 0
max_tokens = 2000
prompt_template = """
Review the following text. Cite specific examples of:

- Spelling or grammattical errors
- Repetitive use of the same words
- Redundant ideas
- Text that is hard to understand

{{__INPUT__}}

# Problems:

-
"""
