engine = "text-davinci-003"
temperature = 0.3
n = 1
top_p=1
frequency_penalty = 0
presence_penalty = 0
max_tokens = 2000
prompt_template = """
Briefly summarise the following text:

{{__INPUT__}}

Summary:
"""
