engine = "text-davinci-003"
temperature = 0.8
n = 1
top_p=1
frequency_penalty = 0
presence_penalty = 0
max_tokens = 1000
prompt_template = """Write a love song based on a summary of the following text.
Use the most common theme for the chorus.

{{__INPUT__}}

Song:
"""
